# Settings webserver
webserver:
    image: wordpress:4.9.8-php7.0-apache
    ports: 
        - "80:80"
    links:
        - "dbserver:mysql"

dbserver:
    # Get myswl image
    image: mysql:5.6
    # data amount
    volumes_from:
        - dataonly
    # Environmental valiables
    environment:
        MYSQL_ROOT_PASSWORD: password

